train_reader {
  cap2det_reader {
    decode_image: false
    input_pattern: "raw-data-coco/2017split/coco17_train.record*"
    interleave_cycle_length: 1
    is_training: true
    shuffle_buffer_size: 2000
    map_num_parallel_calls: 10
    prefetch_buffer_size: 500
    batch_size: 20
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 1000
      }
    }
    preprocess_options {
      random_flip_left_right_prob: 0.5
    }
    max_num_proposals: 500
    batch_resize_scale_value: 1.2
    batch_resize_scale_value: 0.8
    batch_resize_scale_value: 0.6
    batch_resize_scale_value: 0.4
  }
}
eval_reader {
  cap2det_reader {
    decode_image: false
    input_pattern: "raw-data-coco/coco17_val.record*"
    interleave_cycle_length: 1
    is_training: false
    shuffle_buffer_size: 500
    map_num_parallel_calls: 5
    prefetch_buffer_size: 500
    batch_size: 1
    image_resizer {
      keep_aspect_ratio_resizer {
        min_dimension: 1000
      }
    }
    max_num_proposals: 500
  }
}
model {
  [TextModel.ext] {
    label_extractor {
      label_file: 'data/coco_label.txt'
    }
    text_classifier {
      label_file: 'data/coco_label.txt'
      open_vocabulary_file: 'data/coco_open_vocab.txt'
      open_vocabulary_word_embedding_file: 'data/coco_open_vocab_300d.npy'
      text_classifier_checkpoint_file: 'zoo/coco_text_classifier/model.ckpt-50000'
      hidden_units: 400
      dropout_keep_proba: 0.5
      regularizer: 1e-5
      label_threshold: 0.7
    }
  }
}
train_config {
  max_steps: 200000
  learning_rate: 0.1
  learning_rate_decay {
    decay_steps: 20000
    decay_rate: 1.0
    staircase: false
  }
  moving_average_decay: 0.0
  optimizer {
    adagrad {
    }
  }
  sync_replicas: false
  save_summary_steps: 2000
  save_checkpoints_steps: 2000
  keep_checkpoint_max: 10
  log_step_count_steps: 10
}
eval_config {
  steps: 6000
  start_delay_secs: 0
  throttle_secs: 60
}

