train_reader{
  input_pattern: "output/ads_trainval_ssbox_quality.record-*"
  interleave_cycle_length: 1
  is_training: true
  shuffle_buffer_size: 2000
  map_num_parallel_calls: 10
  prefetch_buffer_size: 500
  batch_size: 2
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 1000
    }
  }
  preprocess_options {
    random_flip_left_right_prob: 0.5
  }
  max_num_proposals: 500
  shuffle_proposals: false
  batch_resize_scale_value: 1.2
  batch_resize_scale_value: 0.8
  batch_resize_scale_value: 0.6
  batch_resize_scale_value: 0.4
}
eval_reader{
  input_pattern: "output/ads_test_ssbox_quality.record-*"
  interleave_cycle_length: 1
  is_training: false
  shuffle_buffer_size: 500
  map_num_parallel_calls: 5
  prefetch_buffer_size: 500
  batch_size: 1
  image_resizer {
    keep_aspect_ratio_resizer {
      min_dimension: 1000
    }
  }
  max_num_proposals: 500
}
model {
  [Cap2DetModel.ext] {
    frcnn_options {
      feature_extractor {
        type: 'faster_rcnn_inception_v2'
        first_stage_features_stride: 16
      }
      initial_crop_size: 14
      maxpool_kernel_size: 2
      maxpool_stride: 2
      dropout_keep_prob: 0.5
      dropout_on_feature_map: false
      checkpoint_path: 'zoo/inception_v2_2016_08_28/inception_v2.ckpt'
    }
    eval_min_dimension: 1200
    eval_min_dimension: 800
    eval_min_dimension: 600
    eval_min_dimension: 400
    vocabulary_file: 'configs/ads.vocab'
    synonyms_file: 'configs/ads_synonyms.vocab'
    open_vocabulary_file: 'configs/ads_open_vocab.vocab'
    open_vocabulary_glove_file: 'configs/ads_open_vocab_300d.npy'
    embedding_dims: 300
    label_option: EXTEND_MATCH
    oicr_loss_weight: 0.5
    oicr_iterations: 3
    oicr_iou_threshold: 0.6
    oicr_use_proba_r_given_c: true
    soft_label_threshold: 0.7
    text_classifier_checkpoint_path: 'zoo/coco_text_classifier/model.ckpt-50000'
    fc_hyperparams {
      op: FC
      activation: RELU_6
      regularizer {
        l2_regularizer {
          weight: 0.00001
        }
      }
      initializer {
        truncated_normal_initializer {
          mean: 0.0
          stddev: 0.01
        }
      }
    }
    midn_post_process {
      score_thresh: 0.00001
      iou_thresh: 0.4
      max_size_per_class: 100
      max_total_size: 300
    }
    oicr_post_process {
      score_thresh: 0.00001
      iou_thresh: 0.3
      max_size_per_class: 100
      max_total_size: 300
    }
  }
}
train_config {
  max_steps: 100000
  moving_average_decay: 0.99
  learning_rate: 0.01
  learning_rate_decay {
    decay_steps: 40000
    decay_rate: 1.0
    staircase: true
  }
  optimizer {
    adagrad {
    }
  }
  gradient_multiplier {
    scope: 'first_stage_feature_extraction'
    multiplier: 0.0
  }
  gradient_multiplier {
    scope: 'second_stage_feature_extraction'
    multiplier: 1.0
  }
  gradient_multiplier {
    scope: 'first_stage_feature_extraction/InceptionV2/Mixed_4e'
    multiplier: 1.0
  }
  sync_replicas: false
  save_summary_steps: 2000
  save_checkpoints_steps: 2000
  keep_checkpoint_max: 10
  log_step_count_steps: 10
}
eval_config {
  steps: 10
  start_delay_secs: 0
  throttle_secs: 60
}

